# Generated by Django 5.2 on 2025-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artista', '0001_initial'),
        ('Obra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='Obra',
        ),
        migrations.AddField(
            model_name='artista',
            name='Obra',
            field=models.ManyToManyField(blank=True, to='Obra.obra'),
        ),
    ]
