# Generated by Django 5.2 on 2025-06-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artista', '0002_remove_artista_obra_artista_obra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='Obra',
            new_name='obra',
        ),
    ]
