# Generated by Django 5.2 on 2025-06-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='tecnica_utilizada',
            field=models.CharField(default='Técnica desconocida', max_length=100),
        ),
    ]
