# Generated by Django 5.2 on 2025-06-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0002_obra_tecnica_utilizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='anio_creacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='imagen_obra',
            field=models.ImageField(blank=True, null=True, upload_to='obras/'),
        ),
    ]
